version: '3.8'

services:
  # -----------------------------
  # INFRAESTRUCTURA
  # -----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - dp1_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dp1_network
  
  postgres:
    image: postgres:13
    container_name: postgres_dp1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calidad_aire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dp1:/var/lib/postgresql/data
    networks:
      - dp1_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d calidad_aire"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dataproject1@admin.com
      PGADMIN_DEFAULT_PASSWORD: icjc5
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - dp1_network



  # -----------------------------
  # APLICACIONES
  # -----------------------------
  
  producer:
    build: ./producers
    container_name: python_producer
    depends_on:
      - kafka
    networks:
      - dp1_network
    restart: on-failure 

  consumer:
    build: ./consumers
    container_name: python_consumer
    depends_on:
      - kafka
      - postgres
    networks:
      - dp1_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calidad_aire

  # 3. Transformaci√≥n
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    container_name: dbt_transformer
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt_project:/usr/app/dbt
    networks:
      - dp1_network
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt 
    entrypoint: ["/bin/bash", "-c"]
    command: ["cd /usr/app/dbt && dbt deps && dbt run && tail -f /dev/null"]


  dashboard:
    build: ./dashboard
    container_name: plotly_dashboard
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    networks:
      - dp1_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080" 
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - dp1_network
    depends_on:
      - kafka

volumes:
  postgres_data_dp1:
  pgadmin_data:


networks:
  dp1_network:
    driver: bridge

